using HAMBOX.Modules.Catalog.Domain.Enums;

namespace HAMBOX.Modules.Catalog.Application.Features.ImportExport;

// ---------- Export ----------

/// <summary>Which sections of the graph an export/import should touch. Mirrors the wizard's checkboxes.</summary>
public sealed record CatalogPackageOptions(
    bool IncludeCategories = true,
    bool IncludeVariants = true,
    bool IncludeInventory = true,
    bool IncludeDigitalCodes = false,
    bool IncludeImages = true,
    bool IncludeLocalization = true,
    bool IncludeSuppliers = false);

/// <summary>
/// Either an explicit id list, a server-resolved filter ("selected"/"filtered"), or the entire
/// catalog with no cap — <see cref="BulkProductSelectionResolver"/>'s 2000-row cap exists to protect
/// interactive admin bulk actions and is deliberately bypassed for <see cref="ExportEntireCatalog"/>,
/// since "migrate the whole catalog" is this feature's primary use case.
/// </summary>
public sealed record CatalogExportScope(
    IReadOnlyList<Guid>? ProductIds,
    string? SearchTerm,
    ProductStatus? Status,
    Guid? CategoryId,
    bool SelectAllMatching,
    bool ExportEntireCatalog);

// ---------- Parsed package (shared shape for both writing and reading a .hambox file, and for
// parsing a single-entity xlsx/csv upload) ----------

/// <summary>
/// <see cref="ImportKey"/> is the product's real <see cref="Guid"/> when generated by our own
/// exporter (giving perfect round-trip fidelity), or any unique string a human fills in when
/// hand-authoring a template — it only has to be unique *within this one file*, to let
/// variants/option-groups/codes rows reference "which product". It is never persisted and never
/// used to detect duplicates against the destination database (see <see cref="CatalogDedupeKeys"/>).
/// </summary>
public sealed record ParsedCategoryRow(
    int RowNumber, string Slug, string NameEn, string? NameAr, string? ParentSlug, bool IsActive, int SortOrder);

public sealed record ParsedProductRow(
    int RowNumber, string ImportKey, string NameEn, string? NameAr, string? DescriptionEn, string? DescriptionAr,
    decimal Price, string CategorySlug, string? Status, int StockQuantity,
    IReadOnlyList<string> ImagePaths, IReadOnlyList<string> AdditionalCategorySlugs);

public sealed record ParsedOptionGroupRow(
    string ProductImportKey, string Key, string DisplayName, string? ParentKey, int SortOrder, bool IsRequired);

public sealed record ParsedOptionRow(
    string ProductImportKey, string GroupKey, string Value, string Label, int SortOrder);

/// <summary>
/// <see cref="MembershipPlanId"/> is carried through as informational metadata only — membership
/// plan ids are Commerce-owned and will not exist (or will mean something else) on a different
/// HAMBOX installation, so it is never auto-relinked on import; imported variants land with no
/// membership plan and a validation warning telling the admin to reassign it manually.
/// </summary>
public sealed record ParsedVariantRow(
    int RowNumber, string Sku, string ProductImportKey, decimal? PriceOverride, decimal? ComparePrice,
    string? Status, int LowStockThreshold, Guid? MembershipPlanId, IReadOnlyList<string> SelectedOptionValues);

public sealed record ParsedCodeRow(
    int RowNumber, string VariantSku, string Code, string? SerialNumber, string? Pin,
    decimal? PurchaseCost, string Currency, DateTimeOffset? ExpirationDate, string? BatchName);

public sealed record ParsedSupplierMappingRow(
    string ProductImportKey, string SupplierCode, string ExternalProductId, string? ExternalSku,
    decimal BuyingPrice, string Currency, int Priority);

public sealed record ParsedCatalogPackage(
    IReadOnlyList<ParsedCategoryRow> Categories,
    IReadOnlyList<ParsedProductRow> Products,
    IReadOnlyList<ParsedOptionGroupRow> OptionGroups,
    IReadOnlyList<ParsedOptionRow> Options,
    IReadOnlyList<ParsedVariantRow> Variants,
    IReadOnlyList<ParsedCodeRow> Codes,
    IReadOnlyList<ParsedSupplierMappingRow> SupplierMappings,
    IReadOnlyDictionary<string, byte[]> Images,
    bool CodesEncrypted)
{
    public static ParsedCatalogPackage Empty { get; } = new(
        [], [], [], [], [], [], [],
        new Dictionary<string, byte[]>(), false);
}

// ---------- Validation report (Step 2 of the wizard) ----------

public sealed record CatalogImportRowResult(
    int RowNumber,
    string EntityType,
    string Label,
    CatalogImportRowStatus Status,
    IReadOnlyList<string> Errors);

public sealed record CatalogImportValidationReport(
    Guid UploadId,
    CatalogPackageFormat Format,
    CatalogImportEntityType EntityType,
    int NewCount,
    int UpdatedCount,
    int DuplicateCount,
    int InvalidCount,
    IReadOnlyList<string> Warnings,
    IReadOnlyList<CatalogImportRowResult> Rows);

// ---------- Execute (Step 4) / Summary (Step 5) ----------

public sealed record CatalogPackageSummary(
    int CreatedCount,
    int UpdatedCount,
    int SkippedCount,
    int FailedCount,
    IReadOnlyList<string> Errors);

public sealed record CatalogPackageJobDto(
    Guid Id,
    CatalogPackageDirection Direction,
    CatalogPackageFormat Format,
    CatalogImportEntityType EntityType,
    CatalogPackageJobStatus Status,
    int ProgressPercent,
    string? FileName,
    string? ResultFileName,
    CatalogPackageSummary? Summary,
    string? ErrorMessage);

/// <summary>
/// The keys used to decide "new vs. duplicate" against what's already in the destination
/// database — deliberately independent of <see cref="ParsedProductRow.ImportKey"/> (see its doc
/// comment). Category → <c>Slug</c>. Product → case-insensitive (<c>CategorySlug</c>, <c>NameEn</c>).
/// Variant → <c>Sku</c>. Digital code → <c>CodeHash</c> (SHA-256 of the normalized code, already
/// computed by <see cref="HAMBOX.Modules.Catalog.Domain.Inventory.DigitalInventoryCode.ComputeHash"/>).
/// </summary>
public static class CatalogDedupeKeys
{
    public const string Category = "Slug";
    public const string Product = "CategorySlug+NameEn";
    public const string Variant = "Sku";
    public const string Code = "CodeHash";
}
