using System.Net;
using System.Text;
using System.Text.Json;
using HAMBOX.Application.Abstractions;
using HAMBOX.Modules.Suppliers.Application.Abstractions;
using HAMBOX.Modules.Suppliers.Application.Errors;
using HAMBOX.Modules.Suppliers.Application.Services;
using HAMBOX.Modules.Suppliers.Domain.Fulfillments;
using HAMBOX.Modules.Suppliers.Domain.Suppliers;
using HAMBOX.Modules.Suppliers.Infrastructure.Persistence;
using HAMBOX.Modules.Suppliers.Infrastructure.Providers.Bamboo;
using HAMBOX.Modules.Suppliers.Infrastructure.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;

namespace HAMBOX.IntegrationTests.Suppliers;

/// <summary>
/// Real SQL Server (LocalDB) coverage for the <see cref="SupplierFulfillment"/> claim race — the
/// actual double-purchase guard. Deliberately NOT SQLite: SQL Server's <c>rowversion</c> column is
/// generated by the database engine itself on every INSERT/UPDATE, and EF Core's SQLite provider has
/// no equivalent (a Phase 2 attempt against SQLite failed at schema creation for exactly this reason —
/// see that phase's report). Mirrors <c>VariantPermanentDeleteConcurrencyTests</c>' existing LocalDB
/// pattern in this repo (<c>Server=(localdb)\MSSQLLocalDB</c>, real <c>MigrateAsync</c>, per-test
/// database, <c>EnsureDeletedAsync</c> teardown). Requires a local SQL Server LocalDB instance to be
/// available; if LocalDB cannot be reached, these tests fail loudly (connection error) rather than
/// silently passing or being skipped — that failure itself is the "cannot verify concurrency here"
/// signal called for if the environment doesn't support it.
/// </summary>
public sealed class SupplierFulfillmentConcurrencyTests : IAsyncLifetime
{
    private readonly string _databaseName = $"HamboxSupplierFulfillmentConcurrency_{Guid.NewGuid():N}";
    private string ConnectionString => $"Server=(localdb)\\MSSQLLocalDB;Database={_databaseName};Trusted_Connection=True;TrustServerCertificate=True;";

    public async Task InitializeAsync()
    {
        await using var db = CreateContext();
        await db.Database.MigrateAsync();
    }

    public async Task DisposeAsync()
    {
        await using var db = CreateContext();
        await db.Database.EnsureDeletedAsync();
    }

    private SuppliersDbContext CreateContext()
    {
        var options = new DbContextOptionsBuilder<SuppliersDbContext>()
            .UseSqlServer(ConnectionString, o => o.MigrationsHistoryTable("__EFMigrationsHistory", "suppliers"))
            .Options;
        return new SuppliersDbContext(options, new PassthroughCodeProtector());
    }

    private async Task<(Guid SupplierId, Guid MappingId, Guid FulfillmentId, Guid HamboxReferenceId)> SeedFulfillmentAsync()
    {
        await using var db = CreateContext();

        var supplier = Supplier.Create("Concurrency Test Supplier", $"SUP-{Guid.NewGuid():N}", "Fake", SupplierAuthenticationType.None, null, 0);
        db.Suppliers.Add(supplier);

        var mapping = SupplierProductMapping.Create(supplier.Id, Guid.NewGuid(), "EXT-1", null, null, 1m, "USD", 0);
        db.SupplierProductMappings.Add(mapping);

        var fulfillment = SupplierFulfillment.Create(Guid.NewGuid(), Guid.NewGuid(), supplier.Id, mapping.Id, 1);
        db.SupplierFulfillments.Add(fulfillment);

        await db.SaveChangesAsync();
        return (supplier.Id, mapping.Id, fulfillment.Id, fulfillment.HamboxReferenceId);
    }

    /// <summary>
    /// The exact scenario requested: two separate contexts load the same Pending row, both call
    /// <see cref="SupplierFulfillment.Claim"/>, both attempt <c>SaveChangesAsync</c>. Tests the domain
    /// method + real RowVersion concurrency token directly (not the full orchestration), so the
    /// asserted end state is deliberately still <c>Submitting</c> — this is the claim step in
    /// isolation, proving the DB-level guard exists at all, before Task 2's end-to-end test exercises
    /// it through the real service.
    /// </summary>
    [Fact]
    public async Task Claim_UnderRealSqlServerConcurrentConnections_ExactlyOneWorkerWins()
    {
        var (_, _, fulfillmentId, originalReferenceId) = await SeedFulfillmentAsync();

        await using var workerA = CreateContext();
        await using var workerB = CreateContext();

        var fulfillmentA = await workerA.SupplierFulfillments.FirstAsync(f => f.Id == fulfillmentId);
        var fulfillmentB = await workerB.SupplierFulfillments.FirstAsync(f => f.Id == fulfillmentId);

        fulfillmentA.Claim();
        fulfillmentB.Claim();

        // Genuinely concurrent commit attempts against the same row on real SQL Server.
        var taskA = workerA.SaveChangesAsync();
        var taskB = workerB.SaveChangesAsync();

        var winners = 0;
        DbUpdateConcurrencyException? loserException = null;

        try
        {
            await taskA;
            winners++;
        }
        catch (DbUpdateConcurrencyException ex)
        {
            loserException = ex;
        }

        try
        {
            await taskB;
            winners++;
        }
        catch (DbUpdateConcurrencyException ex)
        {
            loserException = ex;
        }

        Assert.Equal(1, winners);
        Assert.NotNull(loserException);

        await using var verifyDb = CreateContext();
        var persisted = await verifyDb.SupplierFulfillments.AsNoTracking().SingleAsync(f => f.Id == fulfillmentId);

        Assert.Equal(SupplierFulfillmentStatus.Submitting, persisted.Status);
        Assert.Equal(1, persisted.Attempts); // only the winning claim was ever actually persisted
        Assert.Equal(originalReferenceId, persisted.HamboxReferenceId); // immutable, unaffected by the race
    }

    /// <summary>
    /// Same race with more contenders, to reduce the chance a 2-worker race happens to avoid the
    /// interesting timing window.
    /// </summary>
    [Fact]
    public async Task Claim_UnderRealSqlServerConcurrentConnections_ManyWorkers_ExactlyOneWins()
    {
        var (_, _, fulfillmentId, _) = await SeedFulfillmentAsync();
        const int workerCount = 6;

        var successes = 0;
        var concurrencyLosses = 0;

        var tasks = Enumerable.Range(0, workerCount).Select(async _ =>
        {
            await using var worker = CreateContext();
            var fulfillment = await worker.SupplierFulfillments.FirstAsync(f => f.Id == fulfillmentId);

            // With genuinely concurrent workers and real network round-trips, a late reader can load
            // the row only after an earlier worker already committed its claim — it then legitimately
            // sees Status=Submitting already and Claim() correctly refuses it via the domain guard,
            // without ever reaching SaveChangesAsync. That is just as much "losing the race" as a
            // DbUpdateConcurrencyException from two readers who both saw Pending — both are exactly
            // what "only one worker may ever claim this row" is supposed to guarantee, just detected
            // at different layers depending on timing. Production code (ProcessAsync) never hits this
            // path at all, since it checks status before calling Claim() — see the test above this one.
            try
            {
                fulfillment.Claim();
            }
            catch (InvalidOperationException)
            {
                Interlocked.Increment(ref concurrencyLosses);
                return;
            }

            try
            {
                await worker.SaveChangesAsync();
                Interlocked.Increment(ref successes);
            }
            catch (DbUpdateConcurrencyException)
            {
                Interlocked.Increment(ref concurrencyLosses);
            }
        });

        await Task.WhenAll(tasks);

        Assert.Equal(1, successes);
        Assert.Equal(workerCount - 1, concurrencyLosses);
    }

    /// <summary>
    /// End-to-end through the real production orchestrator (<see cref="SupplierFulfillmentService.ProcessAsync"/>),
    /// two separate contexts, genuinely concurrent — this is what directly proves "the losing worker
    /// never reaches <see cref="ISupplierProvider.PurchaseAsync"/>": a shared recording fake provider is
    /// wired into both workers, so if the losing side ever reached the external call, the recorded
    /// call count would be 2, not 1.
    /// </summary>
    [Fact]
    public async Task ProcessAsync_UnderRealSqlServerConcurrentConnections_OnlyTheWinnerEverCallsTheProvider()
    {
        var (_, _, fulfillmentId, _) = await SeedFulfillmentAsync();

        var sharedProvider = new RecordingFakeProvider("Fake");
        var registry = new SupplierProviderRegistry([sharedProvider]);

        await using var dbA = CreateContext();
        await using var dbB = CreateContext();
        var serviceA = new SupplierFulfillmentService(dbA, registry, NullLogger<SupplierFulfillmentService>.Instance);
        var serviceB = new SupplierFulfillmentService(dbB, registry, NullLogger<SupplierFulfillmentService>.Instance);

        var results = await Task.WhenAll(serviceA.ProcessAsync(fulfillmentId), serviceB.ProcessAsync(fulfillmentId));

        Assert.Single(results, r => r.IsSuccess);
        Assert.Single(results, r => r.IsFailure && r.Error == SupplierErrors.ConcurrentClaimLost);

        // The single most important assertion: the external provider was called exactly once, no
        // matter how the two ProcessAsync calls interleaved.
        Assert.Equal(1, sharedProvider.PurchaseCallCount);

        await using var verifyDb = CreateContext();
        var persisted = await verifyDb.SupplierFulfillments.AsNoTracking().SingleAsync(f => f.Id == fulfillmentId);
        Assert.Equal(SupplierFulfillmentStatus.Succeeded, persisted.Status);
        Assert.Equal(1, persisted.DeliveredQuantity);
    }

    /// <summary>
    /// The same guarantee as the test above, but wired with the REAL <see cref="BambooSupplierProvider"/>
    /// (an HTTP call to a fake handler counts invocations) instead of a hand-rolled fake — proving the
    /// claim guard holds for the actual production provider implementation, not just an abstract test
    /// double standing in for "some ISupplierProvider."
    /// </summary>
    [Fact]
    public async Task ProcessAsync_UnderRealSqlServerConcurrentConnections_WithRealBambooProvider_OnlyOnePlaceOrderCall()
    {
        await using var seedDb = CreateContext();
        var supplier = Supplier.Create("Bamboo Concurrency Test", $"SUP-{Guid.NewGuid():N}", "Bamboo", SupplierAuthenticationType.ApiKey, null, 0);
        supplier.UpdateCredentials("test-client-id", "test-client-secret", null, null, null, null);
        supplier.UpdateSettings(JsonSerializer.Serialize(new { accountId = 555 }));
        seedDb.Suppliers.Add(supplier);
        var mapping = SupplierProductMapping.Create(supplier.Id, Guid.NewGuid(), "483243", null, null, 25m, "USD", 0);
        seedDb.SupplierProductMappings.Add(mapping);
        var fulfillment = SupplierFulfillment.Create(Guid.NewGuid(), Guid.NewGuid(), supplier.Id, mapping.Id, 1);
        seedDb.SupplierFulfillments.Add(fulfillment);
        await seedDb.SaveChangesAsync();

        var placeOrderCallCount = 0;
        var handler = new CountingFakeHttpMessageHandler(() =>
        {
            Interlocked.Increment(ref placeOrderCallCount);
            // Bare JSON string, not an object — matches the real sandbox's confirmed Place Order
            // success shape (see BambooHttpClient.PlaceOrderAsync). An object here would make
            // BambooHttpClient's deserialization throw and fall into the ambiguous/Unknown path instead
            // of Submitted, silently defeating the point of exercising the real provider.
            return new HttpResponseMessage(HttpStatusCode.OK)
            {
                Content = new StringContent(JsonSerializer.Serialize(Guid.NewGuid().ToString()), Encoding.UTF8, "application/json"),
            };
        });
        var httpClient = new HttpClient(handler) { BaseAddress = new Uri(BambooProviderConstants.BaseUrl) };
        var bambooOptions = Options.Create(new BambooProviderOptions());
        var bambooHttp = new BambooHttpClient(httpClient, bambooOptions, NullLogger<BambooHttpClient>.Instance);
        var bambooProvider = new BambooSupplierProvider(bambooHttp, NullLogger<BambooSupplierProvider>.Instance);
        var registry = new SupplierProviderRegistry([bambooProvider]);

        await using var dbA = CreateContext();
        await using var dbB = CreateContext();
        var serviceA = new SupplierFulfillmentService(dbA, registry, NullLogger<SupplierFulfillmentService>.Instance);
        var serviceB = new SupplierFulfillmentService(dbB, registry, NullLogger<SupplierFulfillmentService>.Instance);

        var results = await Task.WhenAll(serviceA.ProcessAsync(fulfillment.Id), serviceB.ProcessAsync(fulfillment.Id));

        Assert.Single(results, r => r.IsSuccess);
        Assert.Single(results, r => r.IsFailure && r.Error == SupplierErrors.ConcurrentClaimLost);
        Assert.Equal(1, placeOrderCallCount);

        // With the real bare-string response shape, the winner should reach Submitted (accepted,
        // awaiting reconciliation) rather than Unknown (which a stale/wrong fake shape would silently
        // produce instead via a swallowed JsonException — see the response-shape comment above).
        await using var verifyDb = CreateContext();
        var persisted = await verifyDb.SupplierFulfillments.AsNoTracking().SingleAsync(f => f.Id == fulfillment.Id);
        Assert.Equal(SupplierFulfillmentStatus.Submitted, persisted.Status);
        Assert.NotNull(persisted.ProviderOrderId);
    }

    private sealed class CountingFakeHttpMessageHandler(Func<HttpResponseMessage> responder) : HttpMessageHandler
    {
        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) =>
            Task.FromResult(responder());
    }

    private sealed class PassthroughCodeProtector : ICodeProtector
    {
        public string Protect(string plainText) => plainText;

        public string Unprotect(string cipherText) => cipherText;
    }

    /// <summary>Minimal thread-safe recording fake — only what this test needs (a call counter), separate from the richer <c>FakeSupplierProvider</c> in HAMBOX.UnitTests.</summary>
    private sealed class RecordingFakeProvider(string providerType) : ISupplierProvider
    {
        private int _purchaseCallCount;

        public int PurchaseCallCount => _purchaseCallCount;

        public string ProviderType => providerType;

        public int? MaxQuantityPerPurchase => null;

        public Task<SupplierConnectionTestResult> TestConnectionAsync(SupplierProviderContext context, CancellationToken cancellationToken = default) =>
            Task.FromResult(new SupplierConnectionTestResult(true, "ok"));

        public Task<SupplierCredentialValidationResult> ValidateCredentialsAsync(SupplierProviderContext context, CancellationToken cancellationToken = default) =>
            Task.FromResult(new SupplierCredentialValidationResult(true, null));

        public Task<SupplierProductSyncResult> SyncProductsAsync(SupplierProviderContext context, CancellationToken cancellationToken = default) =>
            Task.FromResult(new SupplierProductSyncResult(false, 0, null));

        public Task<SupplierInventorySyncResult> SyncInventoryAsync(SupplierProviderContext context, CancellationToken cancellationToken = default) =>
            Task.FromResult(new SupplierInventorySyncResult(false, 0, null));

        public Task<SupplierPriceSyncResult> SyncPricesAsync(SupplierProviderContext context, CancellationToken cancellationToken = default) =>
            Task.FromResult(new SupplierPriceSyncResult(false, 0, null));

        public Task<SupplierReservationResult> ReserveAsync(SupplierReservationRequest request, SupplierProviderContext context, CancellationToken cancellationToken = default) =>
            Task.FromResult(new SupplierReservationResult(false, null, null));

        public Task<SupplierPurchaseResult> PurchaseAsync(SupplierPurchaseRequest request, SupplierProviderContext context, CancellationToken cancellationToken = default)
        {
            Interlocked.Increment(ref _purchaseCallCount);
            var codes = Enumerable.Range(1, request.Quantity).Select(i => $"FAKE-CODE-{request.ReferenceId}-{i}").ToArray();
            return Task.FromResult(new SupplierPurchaseResult(true, $"PROV-{request.ReferenceId}", codes, null, null));
        }

        public Task<SupplierCancellationResult> CancelAsync(SupplierCancellationRequest request, SupplierProviderContext context, CancellationToken cancellationToken = default) =>
            Task.FromResult(new SupplierCancellationResult(false, null));

        public Task<SupplierOrderStatusResult> GetOrderStatusAsync(SupplierOrderStatusQuery query, SupplierProviderContext context, CancellationToken cancellationToken = default) =>
            Task.FromResult(new SupplierOrderStatusResult(SupplierProviderOrderStatus.Unknown, null, null, null, null));

        public Task<SupplierAvailabilityResult> GetAvailabilityAsync(SupplierAvailabilityQuery query, SupplierProviderContext context, CancellationToken cancellationToken = default) =>
            Task.FromResult(new SupplierAvailabilityResult(false, [], "not supported by fake"));

        public Task<SupplierCatalogSearchResult> SearchCatalogAsync(SupplierCatalogQuery query, SupplierProviderContext context, CancellationToken cancellationToken = default) =>
            Task.FromResult(new SupplierCatalogSearchResult(false, [], "Catalog search not supported by this fake."));
    }
}
