<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Http" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HAMBOX.Modules.Catalog.Application\HAMBOX.Modules.Catalog.Application.csproj" />
    <ProjectReference Include="..\..\Identity\HAMBOX.Modules.Identity.Application\HAMBOX.Modules.Identity.Application.csproj" />
    <ProjectReference Include="..\..\Identity\HAMBOX.Modules.Identity.Presentation\HAMBOX.Modules.Identity.Presentation.csproj" />
  </ItemGroup>

</Project>
