<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="HAMBOX.IntegrationTests" />
    <InternalsVisibleTo Include="HAMBOX.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HAMBOX.Modules.Commerce.Domain\HAMBOX.Modules.Commerce.Domain.csproj" />
    <ProjectReference Include="..\..\Catalog\HAMBOX.Modules.Catalog.Application\HAMBOX.Modules.Catalog.Application.csproj" />
    <ProjectReference Include="..\..\Themes\HAMBOX.Modules.Themes.Application\HAMBOX.Modules.Themes.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\HAMBOX.Application\HAMBOX.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\HAMBOX.SharedKernel\HAMBOX.SharedKernel.csproj" />
  </ItemGroup>

</Project>
